---
- name: Check that CONSUL exists
  stat:
    path: "{{ consul_dir }}"
  register: consul_repo

- name: Git clone CONSUL
  git:
    repo: https://github.com/consul/consul.git
    dest: "{{ consul_dir }}/releases/0-installer"
    clone: yes
  when: consul_repo.stat.exists == False

- name: Add symbolic link for current release folder
  file:
    state: "link"
    src: "{{ consul_dir }}/releases/0-installer"
    dest: "{{ release_dir }}"
  when: consul_repo.stat.exists == False

- name: Create shared folder
  file:
    path: "{{ shared_dir }}"
    state: directory

- name: Create shared folders
  file:
    path: "{{ shared_dir }}/{{ item }}"
    state: directory
  with_items: "{{ shared_dirs }}"

- name: Remove log folder
  file:
    path: "{{ release_dir }}/log"
    state: absent

- name: Link shared folders
  file:
    state: "link"
    src: "{{ shared_dir }}/{{ item }}"
    dest: "{{ release_dir }}/{{ item }}"
  with_items: "{{ shared_dirs }}"

- name: Create shared config folder
  file:
    path: "{{ shared_dir }}/config"
    state: directory

- name: Create shared public folder
  file:
    path: "{{ shared_dir }}/public"
    state: directory

- name: Create shared public folders
  file:
    path: "{{ shared_dir }}/public/{{ item }}"
    state: directory
  with_items: "{{ shared_public_dirs }}"

- name: Link shared public folders
  file:
    state: "link"
    src: "{{ shared_dir }}/public/{{ item }}"
    dest: "{{ release_dir }}/public/{{ item }}"
  with_items: "{{ shared_public_dirs }}"
